-- Grant schema and all table privileges
GRANT USAGE ON SCHEMA {{SCHEMA}} TO {{USERNAME}};
GRANT {{PRIVILEGES}} ON ALL TABLES IN SCHEMA {{SCHEMA}} TO {{USERNAME}}{{GRANT_OPTION}};
ALTER DEFAULT PRIVILEGES IN SCHEMA {{SCHEMA}} GRANT {{PRIVILEGES}} ON TABLES TO {{USERNAME}}{{GRANT_OPTION}};
