[project]
name = "azure-lakehouse"
version = "0.1.0"
description = "Azure Lakehouseinfrastructure with Pulumi"
requires-python = ">=3.13"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-docker>=4.0.0,<5.0.0",
    "pulumi-kubernetes>=4.0.0,<5.0.0",
    "pulumi-command>=1.0.0,<2.0.0",
    "pyspark==4.0.0",
    "apache-airflow==3.2.0",
    "pip",
    "fastapi",
    "pydantic",
    "aiokafka",
    "pyflink",
    "fastmcp",
    "trino",
    "uvicorn[standard]"
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.4.0",
]
